version: '2'
services:
  kanboard:
    image: kanboard/kanboard:v1.2.44
    ports:
      - "8880:80"
      - "443:443"
    volumes:
      - ./kanboard_data:/var/www/app/data
      - ./kanboard_plugins:/var/www/app/plugins
      - ./kanboard_ssl:/etc/nginx/ssl
    environment:
      - PLUGIN_INSTALLER=true
