version: '2'
services:
  kanboard:
    image: ghcr.io/jogi-k/kanboard:v1.2.46-minute-gran-01
    ports:
      - "8880:80"
      - "443:443"
    volumes:
      - ./kanboard_data:/var/www/app/data
      - ./kanboard_plugins:/var/www/app/plugins
      - ./kanboard_ssl:/etc/nginx/ssl
    environment:
      - PLUGIN_INSTALLER=true
